export { default as TPermissionTree } from './TPermissionTree.vue'
export { default as TMenuTree } from './TMenuTree.vue'
export { default as TDictSelector } from './TDictSelector.vue'
export { default as TRoleSelector } from './TRoleSelector.vue'
export { default as TUserSelector } from './TUserSelector.vue'
export { default as TTenantSelector } from './TTenantSelector.vue'
export { createSelectorComponent, type SelectorOption, type SelectorFetcher } from './_selector-factory'
