/**
 * AUTO-GENERATED by `tools/icons/generate.mjs` - do not edit by hand.
 * Run `pnpm icons:generate` after changing which icons this package renders;
 * `pnpm icons:check` and `dotnet test` both fail when it drifts.
 *
 * Every Iconify name `@tnzi/ui-admin` can render, for applications that bundle
 * their icons instead of letting `@iconify/vue` fetch unknown names from the
 * public Iconify API at render time.
 *
 * Cumulative: this package's own names plus those of `@tnzi/core`, `@tnzi/ui`, `@tnzi/ui-ai`.
 *
 * Includes the icons that only exist in the backend: a module declares one
 * with `[RuntimeSettingGroup(Icon = "mdi:...")]`, it reaches the browser as
 * `SettingsCenterGroupDto.icon`, and it appears in no frontend source at all.
 *
 * Importing this changes nothing on its own. Applications that do not bundle
 * icons keep resolving them over the network exactly as before.
 *
 * @example
 * ```ts
 * import { bundleTnziIcons } from '@tnzi/ui-admin/icons'
 * import { icons as lineMd } from '@iconify-json/line-md'
 * import { icons as lucide } from '@iconify-json/lucide'
 * import { icons as materialSymbols } from '@iconify-json/material-symbols'
 * import { icons as mdi } from '@iconify-json/mdi'
 * import { icons as nimbus } from '@iconify-json/nimbus'
 * import { icons as simpleIcons } from '@iconify-json/simple-icons'
 *
 * bundleTnziIcons([lineMd, lucide, materialSymbols, mdi, nimbus, simpleIcons])
 * ```
 */
import { addCollection, type IconifyJSON } from '@iconify/vue'
import { getIcons } from '@iconify/utils'

/** Every Iconify name `@tnzi/ui-admin` and its @tnzi dependencies can render (564 names, 6 collections). */
export const tnziIconNames: readonly string[] = [
  'line-md:menu-fold-left',
  'line-md:menu-fold-right',
  'lucide:alert-circle',
  'lucide:alert-triangle',
  'lucide:arrow-down',
  'lucide:arrow-right',
  'lucide:arrow-up',
  'lucide:arrow-up-right',
  'lucide:book',
  'lucide:book-open',
  'lucide:bookmark',
  'lucide:bot',
  'lucide:braces',
  'lucide:brain',
  'lucide:check',
  'lucide:check-circle-2',
  'lucide:chevron-down',
  'lucide:chevron-left',
  'lucide:chevron-right',
  'lucide:chevrons-up-down',
  'lucide:circle',
  'lucide:circle-alert',
  'lucide:circle-check',
  'lucide:circle-dashed',
  'lucide:circle-user-round',
  'lucide:clock',
  'lucide:code',
  'lucide:command',
  'lucide:copy',
  'lucide:cpu',
  'lucide:credit-card',
  'lucide:database',
  'lucide:download',
  'lucide:external-link',
  'lucide:file',
  'lucide:file-archive',
  'lucide:file-audio',
  'lucide:file-code',
  'lucide:file-code-2',
  'lucide:file-spreadsheet',
  'lucide:file-text',
  'lucide:file-type',
  'lucide:file-video',
  'lucide:folder',
  'lucide:folder-open',
  'lucide:gauge',
  'lucide:history',
  'lucide:house',
  'lucide:image',
  'lucide:info',
  'lucide:library',
  'lucide:link',
  'lucide:loader-2',
  'lucide:loader-circle',
  'lucide:log-out',
  'lucide:maximize-2',
  'lucide:message-circle',
  'lucide:message-square',
  'lucide:message-square-plus',
  'lucide:mic',
  'lucide:minimize-2',
  'lucide:minus',
  'lucide:monitor',
  'lucide:octagon-pause',
  'lucide:palette',
  'lucide:panel-left',
  'lucide:panel-left-open',
  'lucide:paperclip',
  'lucide:play',
  'lucide:plug',
  'lucide:plus',
  'lucide:presentation',
  'lucide:refresh-ccw',
  'lucide:refresh-cw',
  'lucide:rotate-ccw',
  'lucide:search',
  'lucide:send',
  'lucide:settings',
  'lucide:settings-2',
  'lucide:shield-check',
  'lucide:smartphone',
  'lucide:sparkles',
  'lucide:square',
  'lucide:square-arrow-out-up-right',
  'lucide:square-pen',
  'lucide:star',
  'lucide:table',
  'lucide:table-2',
  'lucide:tablet',
  'lucide:terminal',
  'lucide:thumbs-down',
  'lucide:thumbs-up',
  'lucide:trash-2',
  'lucide:triangle-alert',
  'lucide:unplug',
  'lucide:user',
  'lucide:wand-2',
  'lucide:wrench',
  'lucide:x',
  'lucide:x-circle',
  'lucide:zap',
  'material-symbols:hdr-auto',
  'material-symbols:nightlight-rounded',
  'material-symbols:sunny',
  'material-symbols:sunny-rounded',
  'mdi:ab-testing',
  'mdi:account',
  'mdi:account-arrow-right-outline',
  'mdi:account-cash-outline',
  'mdi:account-check-outline',
  'mdi:account-circle',
  'mdi:account-circle-outline',
  'mdi:account-clock',
  'mdi:account-clock-outline',
  'mdi:account-cog',
  'mdi:account-cog-outline',
  'mdi:account-details-outline',
  'mdi:account-eye-outline',
  'mdi:account-group',
  'mdi:account-group-outline',
  'mdi:account-key-outline',
  'mdi:account-multiple',
  'mdi:account-multiple-check-outline',
  'mdi:account-multiple-outline',
  'mdi:account-outline',
  'mdi:account-plus-outline',
  'mdi:account-search-outline',
  'mdi:account-tie-outline',
  'mdi:alert',
  'mdi:alert-circle',
  'mdi:alert-circle-outline',
  'mdi:alert-outline',
  'mdi:alpha-a-circle-outline',
  'mdi:android',
  'mdi:apple',
  'mdi:apple-ios',
  'mdi:apps',
  'mdi:archive-clock-outline',
  'mdi:arrow-collapse-horizontal',
  'mdi:arrow-down-bold',
  'mdi:arrow-left',
  'mdi:arrow-up-bold',
  'mdi:auto-fix',
  'mdi:autorenew',
  'mdi:backup-restore',
  'mdi:bank-check',
  'mdi:bank-outline',
  'mdi:bank-plus',
  'mdi:bank-transfer',
  'mdi:bank-transfer-in',
  'mdi:bank-transfer-out',
  'mdi:basket-outline',
  'mdi:bell',
  'mdi:bell-alert-outline',
  'mdi:bell-cog-outline',
  'mdi:bell-off-outline',
  'mdi:bell-outline',
  'mdi:bell-ring-outline',
  'mdi:book-alphabet',
  'mdi:book-open-page-variant-outline',
  'mdi:book-open-variant',
  'mdi:book-search-outline',
  'mdi:bookmark',
  'mdi:brain',
  'mdi:briefcase-outline',
  'mdi:broadcast',
  'mdi:broom',
  'mdi:bug-outline',
  'mdi:bullhorn-outline',
  'mdi:bullhorn-variant',
  'mdi:calculator-variant-outline',
  'mdi:calendar',
  'mdi:calendar-account-outline',
  'mdi:calendar-alert',
  'mdi:calendar-blank-outline',
  'mdi:calendar-check-outline',
  'mdi:calendar-clock',
  'mdi:calendar-lock',
  'mdi:calendar-outline',
  'mdi:calendar-plus',
  'mdi:calendar-range',
  'mdi:calendar-remove-outline',
  'mdi:calendar-sync-outline',
  'mdi:call-split',
  'mdi:cancel',
  'mdi:card-account-details-outline',
  'mdi:card-account-mail-outline',
  'mdi:card-text-outline',
  'mdi:cart',
  'mdi:cart-arrow-down',
  'mdi:cart-outline',
  'mdi:cash',
  'mdi:cash-check',
  'mdi:cash-clock',
  'mdi:cash-minus',
  'mdi:cash-multiple',
  'mdi:cash-refund',
  'mdi:cellphone',
  'mdi:cellphone-key',
  'mdi:cellphone-message',
  'mdi:certificate-outline',
  'mdi:chart-areaspline',
  'mdi:chart-bar',
  'mdi:chart-box-outline',
  'mdi:chart-line',
  'mdi:chart-pie',
  'mdi:chart-timeline-variant',
  'mdi:chat',
  'mdi:chat-outline',
  'mdi:chat-processing-outline',
  'mdi:check',
  'mdi:check-circle',
  'mdi:check-circle-outline',
  'mdi:checkbook',
  'mdi:checkbox-blank-outline',
  'mdi:checkbox-marked',
  'mdi:chevron-down',
  'mdi:chevron-left',
  'mdi:chevron-right',
  'mdi:chevron-up',
  'mdi:chip',
  'mdi:circle',
  'mdi:circle-off-outline',
  'mdi:circle-outline',
  'mdi:clipboard-list-outline',
  'mdi:clipboard-text-clock-outline',
  'mdi:clipboard-text-outline',
  'mdi:clock',
  'mdi:clock-alert-outline',
  'mdi:clock-outline',
  'mdi:close',
  'mdi:close-box-multiple-outline',
  'mdi:close-circle',
  'mdi:close-circle-outline',
  'mdi:cloud',
  'mdi:cloud-cog-outline',
  'mdi:cloud-download',
  'mdi:cloud-download-outline',
  'mdi:cloud-off-outline',
  'mdi:cloud-sync-outline',
  'mdi:cloud-upload',
  'mdi:cloud-upload-outline',
  'mdi:code-braces',
  'mdi:code-json',
  'mdi:code-tags',
  'mdi:cog',
  'mdi:cog-off-outline',
  'mdi:cog-outline',
  'mdi:cog-refresh-outline',
  'mdi:comment-alert-outline',
  'mdi:compare-horizontal',
  'mdi:compass-off-outline',
  'mdi:connection',
  'mdi:console',
  'mdi:console-line',
  'mdi:content-copy',
  'mdi:content-duplicate',
  'mdi:content-save',
  'mdi:content-save-outline',
  'mdi:counter',
  'mdi:credit-card',
  'mdi:credit-card-clock-outline',
  'mdi:credit-card-outline',
  'mdi:credit-card-refresh-outline',
  'mdi:credit-card-settings-outline',
  'mdi:cube-off-outline',
  'mdi:cube-outline',
  'mdi:currency-usd',
  'mdi:currency-usd-off',
  'mdi:database',
  'mdi:database-outline',
  'mdi:delete',
  'mdi:delete-outline',
  'mdi:delete-sweep-outline',
  'mdi:devices',
  'mdi:directions-fork',
  'mdi:discord',
  'mdi:domain',
  'mdi:dots-horizontal',
  'mdi:dots-vertical',
  'mdi:download',
  'mdi:download-outline',
  'mdi:drag',
  'mdi:draw-pen',
  'mdi:earth-arrow-right',
  'mdi:email',
  'mdi:email-check-outline',
  'mdi:email-multiple',
  'mdi:email-multiple-outline',
  'mdi:email-off-outline',
  'mdi:email-open-outline',
  'mdi:email-outline',
  'mdi:email-remove-outline',
  'mdi:emoticon-happy-outline',
  'mdi:emoticon-outline',
  'mdi:export',
  'mdi:eye',
  'mdi:eye-off',
  'mdi:eye-off-outline',
  'mdi:eye-outline',
  'mdi:facebook',
  'mdi:fax',
  'mdi:file',
  'mdi:file-cancel-outline',
  'mdi:file-clock-outline',
  'mdi:file-code-outline',
  'mdi:file-delimited-outline',
  'mdi:file-document-edit-outline',
  'mdi:file-document-multiple-outline',
  'mdi:file-document-outline',
  'mdi:file-document-plus-outline',
  'mdi:file-download-outline',
  'mdi:file-excel',
  'mdi:file-excel-box',
  'mdi:file-image',
  'mdi:file-image-outline',
  'mdi:file-multiple',
  'mdi:file-music',
  'mdi:file-music-outline',
  'mdi:file-outline',
  'mdi:file-pdf-box',
  'mdi:file-percent-outline',
  'mdi:file-powerpoint',
  'mdi:file-powerpoint-box',
  'mdi:file-search-outline',
  'mdi:file-sign',
  'mdi:file-table-outline',
  'mdi:file-tree-outline',
  'mdi:file-undo-outline',
  'mdi:file-upload-outline',
  'mdi:file-video',
  'mdi:file-video-outline',
  'mdi:file-word',
  'mdi:file-word-box',
  'mdi:filter',
  'mdi:filter-check-outline',
  'mdi:filter-cog-outline',
  'mdi:filter-outline',
  'mdi:filter-variant',
  'mdi:fire',
  'mdi:flag',
  'mdi:folder',
  'mdi:folder-account-outline',
  'mdi:folder-cog-outline',
  'mdi:folder-multiple-outline',
  'mdi:folder-open',
  'mdi:folder-open-outline',
  'mdi:folder-outline',
  'mdi:folder-plus-outline',
  'mdi:folder-zip',
  'mdi:folder-zip-outline',
  'mdi:form-textbox',
  'mdi:form-textbox-password',
  'mdi:format-color-text',
  'mdi:format-horizontal-align-left',
  'mdi:format-horizontal-align-right',
  'mdi:format-list-bulleted',
  'mdi:format-text',
  'mdi:forum',
  'mdi:forum-outline',
  'mdi:fountain-pen-tip',
  'mdi:fullscreen',
  'mdi:fullscreen-exit',
  'mdi:function-variant',
  'mdi:gavel',
  'mdi:gesture-tap',
  'mdi:gift',
  'mdi:github',
  'mdi:google',
  'mdi:harddisk',
  'mdi:heart',
  'mdi:heart-pulse',
  'mdi:help-circle',
  'mdi:help-circle-outline',
  'mdi:history',
  'mdi:home',
  'mdi:hub',
  'mdi:image-broken-variant',
  'mdi:image-outline',
  'mdi:import',
  'mdi:inbox-outline',
  'mdi:information',
  'mdi:information-outline',
  'mdi:invoice-text-outline',
  'mdi:ip-network-outline',
  'mdi:key',
  'mdi:key-outline',
  'mdi:key-remove',
  'mdi:key-variant',
  'mdi:lan-connect',
  'mdi:language-css3',
  'mdi:language-html5',
  'mdi:language-javascript',
  'mdi:language-markdown',
  'mdi:language-markdown-outline',
  'mdi:language-typescript',
  'mdi:laptop',
  'mdi:layers-triple-outline',
  'mdi:lightbulb-on-outline',
  'mdi:lightbulb-outline',
  'mdi:lightning-bolt-outline',
  'mdi:link',
  'mdi:link-variant',
  'mdi:link-variant-off',
  'mdi:linux',
  'mdi:lock',
  'mdi:lock-open',
  'mdi:lock-open-variant-outline',
  'mdi:lock-outline',
  'mdi:lock-reset',
  'mdi:login',
  'mdi:login-variant',
  'mdi:logout',
  'mdi:logout-variant',
  'mdi:magnify',
  'mdi:map-marker-outline',
  'mdi:menu',
  'mdi:menu-right',
  'mdi:message',
  'mdi:message-badge-outline',
  'mdi:message-cog-outline',
  'mdi:message-flash-outline',
  'mdi:message-text',
  'mdi:message-text-outline',
  'mdi:microsoft',
  'mdi:microsoft-azure',
  'mdi:microsoft-windows',
  'mdi:minus',
  'mdi:minus-circle-outline',
  'mdi:monitor',
  'mdi:note-text-outline',
  'mdi:notebook-outline',
  'mdi:numeric',
  'mdi:office-building-outline',
  'mdi:open-in-new',
  'mdi:package-variant-closed',
  'mdi:palette-outline',
  'mdi:paperclip',
  'mdi:pause',
  'mdi:pause-circle-outline',
  'mdi:pencil',
  'mdi:pencil-outline',
  'mdi:pencil-plus-outline',
  'mdi:percent-outline',
  'mdi:phone-outline',
  'mdi:pin',
  'mdi:pin-off-outline',
  'mdi:pin-outline',
  'mdi:play',
  'mdi:play-circle-outline',
  'mdi:play-outline',
  'mdi:playlist-plus',
  'mdi:plus',
  'mdi:plus-circle-outline',
  'mdi:power',
  'mdi:printer-check',
  'mdi:printer-outline',
  'mdi:progress-check',
  'mdi:pulse',
  'mdi:puzzle-outline',
  'mdi:qrcode',
  'mdi:radar',
  'mdi:receipt-text-check',
  'mdi:receipt-text-check-outline',
  'mdi:receipt-text-minus-outline',
  'mdi:receipt-text-outline',
  'mdi:receipt-text-plus-outline',
  'mdi:refresh',
  'mdi:repeat',
  'mdi:restart',
  'mdi:restore',
  'mdi:robot',
  'mdi:robot-happy-outline',
  'mdi:robot-outline',
  'mdi:router-network',
  'mdi:rss',
  'mdi:ruler-square',
  'mdi:scale-balance',
  'mdi:send',
  'mdi:send-circle-outline',
  'mdi:send-outline',
  'mdi:server',
  'mdi:server-network',
  'mdi:server-network-outline',
  'mdi:server-outline',
  'mdi:set-merge',
  'mdi:share-variant-outline',
  'mdi:shield-account',
  'mdi:shield-account-outline',
  'mdi:shield-alert-outline',
  'mdi:shield-check-outline',
  'mdi:shield-crown-outline',
  'mdi:shield-key-outline',
  'mdi:shield-lock-outline',
  'mdi:shield-search',
  'mdi:sitemap-outline',
  'mdi:slack',
  'mdi:sort',
  'mdi:sort-descending',
  'mdi:sort-numeric-ascending',
  'mdi:source-branch',
  'mdi:speedometer',
  'mdi:star',
  'mdi:stethoscope',
  'mdi:stop-circle-outline',
  'mdi:swap-horizontal',
  'mdi:table',
  'mdi:tablet',
  'mdi:tag',
  'mdi:tag-multiple-outline',
  'mdi:tag-outline',
  'mdi:target',
  'mdi:test-tube',
  'mdi:text-account',
  'mdi:text-box-outline',
  'mdi:text-box-search-outline',
  'mdi:text-short',
  'mdi:theme-light-dark',
  'mdi:ticket-percent-outline',
  'mdi:timeline-text-outline',
  'mdi:timer-alert-outline',
  'mdi:timer-sand',
  'mdi:toggle-switch-outline',
  'mdi:tools',
  'mdi:transit-connection-variant',
  'mdi:translate',
  'mdi:trash-can-outline',
  'mdi:tray-arrow-down',
  'mdi:tray-arrow-up',
  'mdi:tray-full',
  'mdi:trophy-outline',
  'mdi:truck-outline',
  'mdi:tune',
  'mdi:tune-variant',
  'mdi:twitter',
  'mdi:undo-variant',
  'mdi:unfold-less-horizontal',
  'mdi:unfold-more-horizontal',
  'mdi:upload',
  'mdi:upload-outline',
  'mdi:view-dashboard',
  'mdi:view-dashboard-outline',
  'mdi:view-grid',
  'mdi:view-grid-outline',
  'mdi:view-list',
  'mdi:wallet-outline',
  'mdi:weather-night',
  'mdi:weather-sunny',
  'mdi:weather-windy',
  'mdi:web',
  'mdi:wechat',
  'mdi:wifi',
  'mdi:wifi-off',
  'mdi:window-maximize',
  'mdi:window-restore',
  'mdi:wrench',
  'mdi:wrench-outline',
  'nimbus:chat-dots',
  'simple-icons:anthropic',
  'simple-icons:cursor',
  'simple-icons:github',
  'simple-icons:ollama',
  'simple-icons:openai',
  'simple-icons:vercel',
]

const bareNames = (prefix: string): readonly string[] =>
  tnziIconNames.filter((n) => n.startsWith(`${prefix}:`)).map((n) => n.slice(prefix.length + 1))

/**
 * {@link tnziIconNames} grouped by Iconify collection, so a bundling step can load one collection at a time.
 *
 * ★ The values are **bare** names (`alert-circle`), not qualified ones
 * (`lucide:alert-circle`): the key already carries the collection, and bare is
 * what `getIcons()` and `IconifyJSON.icons` speak. Handing `getIcons` qualified
 * names is not an error, it is a *silent* miss - it returns `null`,
 * `addCollection` accepts that, and every icon renders blank. Use
 * {@link tnziIconNames} when you want the qualified form.
 */
export const tnziIconsByPrefix: Readonly<Record<string, readonly string[]>> = {
  'line-md': bareNames('line-md'),
  'lucide': bareNames('lucide'),
  'material-symbols': bareNames('material-symbols'),
  'mdi': bareNames('mdi'),
  'nimbus': bareNames('nimbus'),
  'simple-icons': bareNames('simple-icons'),
}

/** What a bundling step could *not* do. Empty fields mean every icon is accounted for. */
export interface TnziIconBundleReport {
  /** Icons resolved out of the collections that were passed. */
  readonly loaded: number
  /** Collections this manifest needs that the caller did not pass. */
  readonly missingCollections: readonly string[]
  /** Qualified names that stayed unresolved, including every name from a missing collection. */
  readonly unresolved: readonly string[]
}

/** {@link selectTnziIcons}: the trimmed collections, plus what it could not find. */
export interface TnziIconSelection extends TnziIconBundleReport {
  /** One `IconifyJSON` per collection, carrying only this manifest's icons. */
  readonly subsets: readonly IconifyJSON[]
}

/**
 * Trims full Iconify collections down to just the icons this manifest names.
 *
 * ★ Use this at **build time** and write the result to a JSON file. Measured on
 * this manifest: 170 KB of glyphs versus 17 MB of collections, a 100x difference.
 * The reason is that `getIcons` runs at runtime, but a static `import` of
 * `@iconify-json/material-symbols` puts all 8 MB of it in the bundle first, and
 * no bundler can tree-shake *inside* a JSON object. {@link bundleTnziIcons}
 * pays that price for the convenience of a one-liner; this does not.
 *
 * Pure - it touches no icon storage, so it is safe to call from a Node script.
 */
export function selectTnziIcons(collections: readonly IconifyJSON[]): TnziIconSelection {
  const byPrefix = new Map(collections.map((collection) => [collection.prefix, collection]))
  const subsets: IconifyJSON[] = []
  const missingCollections: string[] = []
  const unresolved: string[] = []
  let loaded = 0

  for (const [prefix, names] of Object.entries(tnziIconsByPrefix)) {
    const qualify = (name: string) => `${prefix}:${name}`
    const collection = byPrefix.get(prefix)
    if (!collection) {
      missingCollections.push(prefix)
      unresolved.push(...names.map(qualify))
      continue
    }

    // `[...names]` because the published type is `readonly string[]` and
    // `getIcons` takes a mutable one. `getIcons` resolves alias chains, so the
    // subset can carry a name under either key; both count as resolved.
    const subset = getIcons(collection, [...names])
    if (!subset) {
      unresolved.push(...names.map(qualify))
      continue
    }

    subsets.push(subset)
    const resolved = new Set([
      ...Object.keys(subset.icons ?? {}),
      ...Object.keys(subset.aliases ?? {}),
    ])
    // Count the *requested* names that resolved, not the subset's entries:
    // resolving an alias pulls its parent in too, so the subset can hold more
    // icons than were asked for.
    loaded += names.filter((name) => resolved.has(name)).length
    unresolved.push(...names.filter((name) => !resolved.has(name)).map(qualify))
  }

  return { subsets, loaded, missingCollections, unresolved }
}

/**
 * Registers every icon in this manifest with `@iconify/vue`, so `<Icon>` stops
 * reaching for the public Iconify API at render time.
 *
 * Pass the collections as data - `import { icons as mdi } from '@iconify-json/mdi'`.
 * Each one carries its own `prefix`, so order and naming do not matter.
 *
 * ★ The imports must be **static**. A loop doing
 * `import(`@iconify-json/${prefix}/icons.json`)` reads well and does not
 * survive bundling: the specifier is a bare package name built from a variable,
 * so Vite cannot analyse it, leaves it verbatim, and the browser then fails to
 * resolve it at runtime - with no build error and no warning.
 *
 * ★ This is the convenient path, not the small one. It puts the **whole** of
 * every collection in your bundle. If that matters, use {@link selectTnziIcons}
 * in a build step and `addCollection` the saved subsets instead.
 *
 * @returns what could not be loaded. Ignoring it is safe; reading it is how you
 * find out a collection is missing before your users see blank squares.
 */
export function bundleTnziIcons(collections: readonly IconifyJSON[]): TnziIconBundleReport {
  const { subsets, ...report } = selectTnziIcons(collections)
  for (const subset of subsets) addCollection(subset)
  return report
}
