export { default as TDetailLayout } from './TDetailLayout.vue'
export { default as TDetailHost } from './TDetailHost.vue'
export type { TDetailHostProps } from './TDetailHost.vue'
export { default as TDetailSection } from './TDetailSection.vue'
export { default as TRecordHeader } from './TRecordHeader.vue'
export type { RecordBadge, RecordFact } from './TRecordHeader.vue'
