<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tnzi.AI\Tnzi.AI.csproj" />
    <ProjectReference Include="..\Tnzi.AspNetCore\Tnzi.AspNetCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TextCopy" Version="6.2.1" />
  </ItemGroup>
</Project>
