/**
 * AUTO-GENERATED by `tools/icons/generate.mjs` - do not edit by hand.
 * Run `pnpm icons:generate` after changing which icons this package renders;
 * `pnpm icons:check` and `dotnet test` both fail when it drifts.
 *
 * Every Iconify name `@tnzi/core` can render, for applications that bundle
 * their icons instead of letting `@iconify/vue` fetch unknown names from the
 * public Iconify API at render time.
 *
 * Cumulative: this is the base package, so these are its own names only.
 *
 * Importing this changes nothing on its own. Applications that do not bundle
 * icons keep resolving them over the network exactly as before.
 *
 * This package is headless and ships the list only. To actually load these
 * icons, use `bundleTnziIcons` from `@tnzi/ui/icons` (or `@tnzi/ui-ai` /
 * `@tnzi/ui-admin`) - its manifest already includes every name below.
 */
/** Every Iconify name `@tnzi/core` and its @tnzi dependencies can render (6 names, 1 collection). */
export const tnziIconNames: readonly string[] = [
  'mdi:android',
  'mdi:apple',
  'mdi:apple-ios',
  'mdi:devices',
  'mdi:linux',
  'mdi:microsoft-windows',
]

const bareNames = (prefix: string): readonly string[] =>
  tnziIconNames.filter((n) => n.startsWith(`${prefix}:`)).map((n) => n.slice(prefix.length + 1))

/**
 * {@link tnziIconNames} grouped by Iconify collection, so a bundling step can load one collection at a time.
 *
 * ★ The values are **bare** names (`alert-circle`), not qualified ones
 * (`lucide:alert-circle`): the key already carries the collection, and bare is
 * what `getIcons()` and `IconifyJSON.icons` speak. Handing `getIcons` qualified
 * names is not an error, it is a *silent* miss - it returns `null`,
 * `addCollection` accepts that, and every icon renders blank. Use
 * {@link tnziIconNames} when you want the qualified form.
 */
export const tnziIconsByPrefix: Readonly<Record<string, readonly string[]>> = {
  'mdi': bareNames('mdi'),
}
