namespace Tnzi.AI.Tests.Skills;

/// <summary>
/// SkillMarkdownParser 安全验证集成测试 — 验证 frontmatter 安全检查
/// </summary>
public class SkillMarkdownParserSecurityTests
{
    [Fact]
    public void Parse_ValidFrontmatter_ReturnsSkill()
    {
        var content = """
            ---
            name: test-skill
            description: A test skill for testing
            version: 1.0
            tags: test,skill
            ---
            ## Knowledge
            Some content here
            """;

        var result = SkillMarkdownParser.Parse(content, "/skills/test/SKILL.md");

        result.ShouldNotBeNull();
        result!.Name.ShouldBe("test-skill");
    }

    [Fact]
    public void Parse_UnknownFrontmatterKey_ReturnsNull()
    {
        var content = """
            ---
            name: test-skill
            description: A test skill
            evil_payload: malicious
            ---
            Content
            """;

        var result = SkillMarkdownParser.Parse(content, "/skills/test/SKILL.md");

        result.ShouldBeNull();
    }

    [Fact]
    public void Parse_DescriptionWithAngleBrackets_ReturnsNull()
    {
        var content = """
            ---
            name: test-skill
            description: <script>alert(1)</script>
            ---
            Content
            """;

        var result = SkillMarkdownParser.Parse(content, "/skills/test/SKILL.md");

        result.ShouldBeNull();
    }

    [Fact]
    public void Parse_InvalidSlugFormat_ReturnsNull()
    {
        var content = """
            ---
            name: test-skill
            slug: INVALID_SLUG
            description: A test skill
            ---
            Content
            """;

        var result = SkillMarkdownParser.Parse(content, "/skills/test/SKILL.md");

        result.ShouldBeNull();
    }

    [Fact]
    public void Parse_ValidSlug_ReturnsSkill()
    {
        var content = """
            ---
            name: My Skill
            slug: my-skill
            description: A valid skill
            ---
            Content
            """;

        var result = SkillMarkdownParser.Parse(content, "/skills/my-skill/SKILL.md");

        result.ShouldNotBeNull();
        result!.Slug.ShouldBe("my-skill");
    }

    [Fact]
    public void Parse_NoSlug_AutoGeneratedFromName()
    {
        var content = """
            ---
            name: web-search
            description: A web search skill
            ---
            Content
            """;

        var result = SkillMarkdownParser.Parse(content, "/skills/web-search/SKILL.md");

        result.ShouldNotBeNull();
        result!.Slug.ShouldBe("web-search");
    }
}
