/**
 * Regenerates `packages/<pkg>/src/icons/index.ts`, the published answer to
 * "which Iconify names does the framework render?" plus the helper that loads
 * them.
 *
 *   node tools/icons/generate.mjs           # rewrite the manifests
 *   node tools/icons/generate.mjs --check   # fail if they drift from the source
 *
 * `--check` is the fast, frontend-side gate. The load-bearing ones are
 * `tests/Tnzi.Architecture.Tests/IconManifestTests`, which runs in `dotnet test`
 * and re-derives both halves independently of this script, and
 * `packages/ui-admin/__tests__/icons/`, which bundles the documented recipe with
 * a real Vite build and then asks `@iconify/vue` whether the icons arrived.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  BUNDLER_SOURCE,
  ICON_PACKAGES,
  MANIFEST_RELATIVE_PATH,
  buildManifest,
  findUnknownPrefixCandidates,
  groupByPrefix,
  renderBundlingRecipe,
} from './icon-manifest.mjs';

const uiRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const repoRoot = join(uiRoot, '..', '..');

// Shares MANIFEST_RELATIVE_PATH with the scanner on purpose: that constant is
// what excludes the manifest from the scan, so writing it anywhere else would
// silently make every package's set absorb its own output.
const manifestPath = (packageName) =>
  join(uiRoot, 'packages', packageName, 'src', MANIFEST_RELATIVE_PATH);

const asJsDoc = (text) =>
  text.split('\n').map((line) => (line ? ` * ${line}` : ' *')).join('\n');

function renderManifest(pkg, names) {
  const grouped = groupByPrefix(names);
  const collections = Object.keys(grouped).sort();
  const backendNote = pkg.includeBackend
    ? ` * Includes the icons that only exist in the backend: a module declares one\n`
      + ` * with \`[RuntimeSettingGroup(Icon = "mdi:...")]\`, it reaches the browser as\n`
      + ` * \`SettingsCenterGroupDto.icon\`, and it appears in no frontend source at all.\n *\n`
    : '';
  const inherited = pkg.dependsOn.length > 0
    ? ` * Cumulative: this package's own names plus those of ${pkg.dependsOn.map((d) => `\`@tnzi/${d}\``).join(', ')}.\n *\n`
    : ` * Cumulative: this is the base package, so these are its own names only.\n *\n`;

  // Core ships data only - see ICON_PACKAGES for why it must not import
  // `@iconify/vue`. Point its readers at the layer that does have the helper
  // rather than leaving them to rediscover the recipe.
  const usage = pkg.bundler
    ? ` * @example\n * \`\`\`ts\n${asJsDoc(renderBundlingRecipe(pkg.name, collections))}\n * \`\`\`\n`
    : ` * This package is headless and ships the list only. To actually load these\n`
      + ` * icons, use \`bundleTnziIcons\` from \`@tnzi/ui/icons\` (or \`@tnzi/ui-ai\` /\n`
      + ` * \`@tnzi/ui-admin\`) - its manifest already includes every name below.\n`;

  const imports = pkg.bundler
    ? `import { addCollection, type IconifyJSON } from '@iconify/vue'\n`
      + `import { getIcons } from '@iconify/utils'\n\n`
    : '';

  const helper = pkg.bundler ? `\n\n${BUNDLER_SOURCE}\n` : '\n';

  return `/**
 * AUTO-GENERATED by \`tools/icons/generate.mjs\` - do not edit by hand.
 * Run \`pnpm icons:generate\` after changing which icons this package renders;
 * \`pnpm icons:check\` and \`dotnet test\` both fail when it drifts.
 *
 * Every Iconify name \`@tnzi/${pkg.name}\` can render, for applications that bundle
 * their icons instead of letting \`@iconify/vue\` fetch unknown names from the
 * public Iconify API at render time.
 *
${inherited}${backendNote} * Importing this changes nothing on its own. Applications that do not bundle
 * icons keep resolving them over the network exactly as before.
 *
${usage} */
${imports}/** Every Iconify name \`@tnzi/${pkg.name}\` and its @tnzi dependencies can render (${names.length} names, ${collections.length} collection${collections.length === 1 ? '' : 's'}). */
export const tnziIconNames: readonly string[] = [
${names.map((name) => `  '${name}',`).join('\n')}
]

const bareNames = (prefix: string): readonly string[] =>
  tnziIconNames.filter((n) => n.startsWith(\`\${prefix}:\`)).map((n) => n.slice(prefix.length + 1))

/**
 * {@link tnziIconNames} grouped by Iconify collection, so a bundling step can load one collection at a time.
 *
 * ★ The values are **bare** names (\`alert-circle\`), not qualified ones
 * (\`lucide:alert-circle\`): the key already carries the collection, and bare is
 * what \`getIcons()\` and \`IconifyJSON.icons\` speak. Handing \`getIcons\` qualified
 * names is not an error, it is a *silent* miss - it returns \`null\`,
 * \`addCollection\` accepts that, and every icon renders blank. Use
 * {@link tnziIconNames} when you want the qualified form.
 */
export const tnziIconsByPrefix: Readonly<Record<string, readonly string[]>> = {
${collections.map((prefix) => `  '${prefix}': bareNames('${prefix}'),`).join('\n')}
}${helper}`;
}

const check = process.argv.includes('--check');
const { manifest, own, backend } = buildManifest(uiRoot, repoRoot);

const unknown = findUnknownPrefixCandidates(uiRoot, repoRoot);
if (unknown.length > 0) {
  const report = [...new Map(unknown.map((u) => [`${u.name}@${u.file}`, u])).values()]
    .map((u) => `  - ${u.name}  (${u.file})`)
    .join('\n');
  console.error(
    `Icon manifest: ${unknown.length} icon reference(s) use a collection that is not in ICON_PREFIXES.\n`
    + `Every name in that collection is missing from the manifest, and a downstream that\n`
    + `bundles icons would render blanks for them. Add the collection to ICON_PREFIXES in\n`
    + `tools/icons/icon-manifest.mjs (or fix the reference):\n${report}`,
  );
  process.exit(1);
}

const drifted = [];
for (const pkg of ICON_PACKAGES) {
  const path = manifestPath(pkg.name);
  const expected = renderManifest(pkg, manifest.get(pkg.name));
  let actual = null;
  try {
    // Compare content, not line endings: on a Windows checkout git hands the
    // committed manifest back with CRLF while the renderer emits LF, and a
    // byte comparison then reported every single name as "missing" while the
    // same tree passed on the Linux runner (2026-09-04).
    actual = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
  } catch {
    /* not generated yet */
  }
  if (actual === expected) continue;

  if (check) {
    drifted.push({ pkg: pkg.name, path, actual, expected, names: manifest.get(pkg.name) });
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, expected, 'utf8');
  console.log(
    `wrote ${relative(repoRoot, path).split(sep).join('/')}`
    + ` (${manifest.get(pkg.name).length} names, ${own.get(pkg.name).size} of them its own`
    + `${pkg.includeBackend ? `, ${backend.size} from the backend` : ''})`,
  );
}

if (!check) {
  process.exit(0);
}

if (drifted.length > 0) {
  const nameOf = (line) => /^ {2}'([^']+)',$/.exec(line)?.[1];
  const namesIn = (text) => new Set((text ?? '').split('\n').map(nameOf).filter(Boolean));
  const report = drifted
    .map(({ pkg, actual, names }) => {
      const committed = namesIn(actual);
      const missing = names.filter((n) => !committed.has(n));
      const stale = [...committed].filter((n) => !names.includes(n));
      const detail = [
        missing.length > 0 ? `      missing: ${missing.join(', ')}` : null,
        stale.length > 0 ? `      no longer referenced: ${stale.join(', ')}` : null,
        missing.length === 0 && stale.length === 0 ? '      (formatting/header/helper only)' : null,
      ].filter(Boolean).join('\n');
      return `  - @tnzi/${pkg}\n${detail}`;
    })
    .join('\n');
  console.error(
    `Icon manifest is out of date with the source in ${drifted.length} package(s).\n`
    + `A downstream that bundled the committed list would render a blank square - no error,\n`
    + `no failed request - for every missing name. Run \`pnpm icons:generate\`.\n${report}`,
  );
  process.exit(1);
}

console.log(`Icon manifest is up to date (${manifest.get('ui-admin').length} names, ${backend.size} of them backend-only).`);
