export { default as TPageHeader } from './TPageHeader.vue'
export { default as TContentPage } from './TContentPage.vue'
export { default as TTabsPage } from './TTabsPage.vue'
export type { TabSection } from './TTabsPage.vue'
export { default as TMasterDetailLayout } from './TMasterDetailLayout.vue'
