/**
 * AUTO-GENERATED by `tools/icons/generate.mjs` - do not edit by hand.
 * Run `pnpm icons:generate` after changing which icons this package renders;
 * `pnpm icons:check` and `dotnet test` both fail when it drifts.
 *
 * Every Iconify name `@tnzi/ui` can render, for applications that bundle
 * their icons instead of letting `@iconify/vue` fetch unknown names from the
 * public Iconify API at render time.
 *
 * Cumulative: this package's own names plus those of `@tnzi/core`.
 *
 * Importing this changes nothing on its own. Applications that do not bundle
 * icons keep resolving them over the network exactly as before.
 *
 * @example
 * ```ts
 * import { bundleTnziIcons } from '@tnzi/ui/icons'
 * import { icons as lineMd } from '@iconify-json/line-md'
 * import { icons as mdi } from '@iconify-json/mdi'
 *
 * bundleTnziIcons([lineMd, mdi])
 * ```
 */
import { addCollection, type IconifyJSON } from '@iconify/vue'
import { getIcons } from '@iconify/utils'

/** Every Iconify name `@tnzi/ui` and its @tnzi dependencies can render (52 names, 2 collections). */
export const tnziIconNames: readonly string[] = [
  'line-md:menu-fold-left',
  'line-md:menu-fold-right',
  'mdi:alert-circle-outline',
  'mdi:android',
  'mdi:apple',
  'mdi:apple-ios',
  'mdi:arrow-down-bold',
  'mdi:arrow-up-bold',
  'mdi:check-circle-outline',
  'mdi:close',
  'mdi:close-circle-outline',
  'mdi:code-tags',
  'mdi:database',
  'mdi:devices',
  'mdi:drag',
  'mdi:facebook',
  'mdi:file-document-outline',
  'mdi:file-excel-box',
  'mdi:file-outline',
  'mdi:file-pdf-box',
  'mdi:file-word-box',
  'mdi:folder-cog-outline',
  'mdi:folder-outline',
  'mdi:folder-zip-outline',
  'mdi:fullscreen',
  'mdi:fullscreen-exit',
  'mdi:github',
  'mdi:google',
  'mdi:help-circle-outline',
  'mdi:image-broken-variant',
  'mdi:inbox-outline',
  'mdi:information-outline',
  'mdi:laptop',
  'mdi:lightbulb-outline',
  'mdi:linux',
  'mdi:login-variant',
  'mdi:microsoft',
  'mdi:microsoft-windows',
  'mdi:minus',
  'mdi:package-variant-closed',
  'mdi:pin',
  'mdi:pin-outline',
  'mdi:plus',
  'mdi:puzzle-outline',
  'mdi:refresh',
  'mdi:theme-light-dark',
  'mdi:translate',
  'mdi:tune',
  'mdi:twitter',
  'mdi:weather-night',
  'mdi:weather-sunny',
  'mdi:wechat',
]

const bareNames = (prefix: string): readonly string[] =>
  tnziIconNames.filter((n) => n.startsWith(`${prefix}:`)).map((n) => n.slice(prefix.length + 1))

/**
 * {@link tnziIconNames} grouped by Iconify collection, so a bundling step can load one collection at a time.
 *
 * ★ The values are **bare** names (`alert-circle`), not qualified ones
 * (`lucide:alert-circle`): the key already carries the collection, and bare is
 * what `getIcons()` and `IconifyJSON.icons` speak. Handing `getIcons` qualified
 * names is not an error, it is a *silent* miss - it returns `null`,
 * `addCollection` accepts that, and every icon renders blank. Use
 * {@link tnziIconNames} when you want the qualified form.
 */
export const tnziIconsByPrefix: Readonly<Record<string, readonly string[]>> = {
  'line-md': bareNames('line-md'),
  'mdi': bareNames('mdi'),
}

/** What a bundling step could *not* do. Empty fields mean every icon is accounted for. */
export interface TnziIconBundleReport {
  /** Icons resolved out of the collections that were passed. */
  readonly loaded: number
  /** Collections this manifest needs that the caller did not pass. */
  readonly missingCollections: readonly string[]
  /** Qualified names that stayed unresolved, including every name from a missing collection. */
  readonly unresolved: readonly string[]
}

/** {@link selectTnziIcons}: the trimmed collections, plus what it could not find. */
export interface TnziIconSelection extends TnziIconBundleReport {
  /** One `IconifyJSON` per collection, carrying only this manifest's icons. */
  readonly subsets: readonly IconifyJSON[]
}

/**
 * Trims full Iconify collections down to just the icons this manifest names.
 *
 * ★ Use this at **build time** and write the result to a JSON file. Measured on
 * this manifest: 170 KB of glyphs versus 17 MB of collections, a 100x difference.
 * The reason is that `getIcons` runs at runtime, but a static `import` of
 * `@iconify-json/material-symbols` puts all 8 MB of it in the bundle first, and
 * no bundler can tree-shake *inside* a JSON object. {@link bundleTnziIcons}
 * pays that price for the convenience of a one-liner; this does not.
 *
 * Pure - it touches no icon storage, so it is safe to call from a Node script.
 */
export function selectTnziIcons(collections: readonly IconifyJSON[]): TnziIconSelection {
  const byPrefix = new Map(collections.map((collection) => [collection.prefix, collection]))
  const subsets: IconifyJSON[] = []
  const missingCollections: string[] = []
  const unresolved: string[] = []
  let loaded = 0

  for (const [prefix, names] of Object.entries(tnziIconsByPrefix)) {
    const qualify = (name: string) => `${prefix}:${name}`
    const collection = byPrefix.get(prefix)
    if (!collection) {
      missingCollections.push(prefix)
      unresolved.push(...names.map(qualify))
      continue
    }

    // `[...names]` because the published type is `readonly string[]` and
    // `getIcons` takes a mutable one. `getIcons` resolves alias chains, so the
    // subset can carry a name under either key; both count as resolved.
    const subset = getIcons(collection, [...names])
    if (!subset) {
      unresolved.push(...names.map(qualify))
      continue
    }

    subsets.push(subset)
    const resolved = new Set([
      ...Object.keys(subset.icons ?? {}),
      ...Object.keys(subset.aliases ?? {}),
    ])
    // Count the *requested* names that resolved, not the subset's entries:
    // resolving an alias pulls its parent in too, so the subset can hold more
    // icons than were asked for.
    loaded += names.filter((name) => resolved.has(name)).length
    unresolved.push(...names.filter((name) => !resolved.has(name)).map(qualify))
  }

  return { subsets, loaded, missingCollections, unresolved }
}

/**
 * Registers every icon in this manifest with `@iconify/vue`, so `<Icon>` stops
 * reaching for the public Iconify API at render time.
 *
 * Pass the collections as data - `import { icons as mdi } from '@iconify-json/mdi'`.
 * Each one carries its own `prefix`, so order and naming do not matter.
 *
 * ★ The imports must be **static**. A loop doing
 * `import(`@iconify-json/${prefix}/icons.json`)` reads well and does not
 * survive bundling: the specifier is a bare package name built from a variable,
 * so Vite cannot analyse it, leaves it verbatim, and the browser then fails to
 * resolve it at runtime - with no build error and no warning.
 *
 * ★ This is the convenient path, not the small one. It puts the **whole** of
 * every collection in your bundle. If that matters, use {@link selectTnziIcons}
 * in a build step and `addCollection` the saved subsets instead.
 *
 * @returns what could not be loaded. Ignoring it is safe; reading it is how you
 * find out a collection is missing before your users see blank squares.
 */
export function bundleTnziIcons(collections: readonly IconifyJSON[]): TnziIconBundleReport {
  const { subsets, ...report } = selectTnziIcons(collections)
  for (const subset of subsets) addCollection(subset)
  return report
}
