export * from './useColumnSettings'
export * from './rowActions'
export * from './useBatchActions'
export * from './useFormModal'
export * from './useCrudPage'
export * from './useEmptyCreateCta'
export * from './useAdminMenu'
export * from './usePermissionGuard'
export * from './useTabContext'
export * from './useAdminModuleManifest'
export * from './useFormRules'
export * from './useNaiveForm'
export * from './useEcharts'
export * from './useRouteProgress'
export * from './useBreakpoint'
export * from './useNotificationSound'
export * from './useChatRealtime'
// 0.2.72+ (B5): exposed for advanced consumers who want the layout-mode
// derivations without mounting TAdminShell (e.g. building a custom
// shell, headless E2E checks).
export * from './useAdminShellLayout'
export { useDetail } from './useDetail'
export type { DetailMode, DetailAction, DetailLayout, DetailSection, UseDetailOptions, UseDetailReturn } from './useDetail'
