/**
 * How many digits a one-time code has, per method.
 *
 * Two different sources, and mixing them up locks people out:
 *
 * - **Email / SMS codes** are generated by the backend with
 *   `Identity:Otp:CodeLength` (4-8, default 6). It is a runtime setting, and
 *   `GET /auth/config` reports the current value as `otpCodeLength`. This
 *   covers code login, quick register, password recovery, email / SMS
 *   two-factor, step-up, contact change and email confirmation.
 * - **Authenticator (TOTP) codes** are always 6 digits (RFC 6238 as used by
 *   the backend's authenticator token provider; the enrolment URI pins
 *   `digits=6`). They do NOT follow `otpCodeLength`.
 *
 * An input fixed at 6 cells on a deployment configured for 8 cannot accept
 * the code the user was sent, so every code entry for an email / SMS code must
 * size itself from {@link resolveOtpCodeLength}.
 */

import type { AuthConfigDto } from './types';

/** Digits in an email / SMS code when the backend does not say (older backends omit the field). */
export const DEFAULT_OTP_CODE_LENGTH = 6;

/** Digits in an authenticator-app (TOTP) code. Fixed by the standard, not configurable. */
export const TOTP_CODE_LENGTH = 6;

/**
 * Upper bound accepted from the wire. The backend validates 4-8; anything
 * outside a sane range is treated as garbage (a boxed OTP input with 500
 * cells is worse than the default) rather than trusted.
 */
const MAX_ACCEPTED_CODE_LENGTH = 12;

/**
 * The email / SMS code length a deployment uses, from its `GET /auth/config`
 * payload (or the bare number). Falls back to {@link DEFAULT_OTP_CODE_LENGTH}
 * when the config is missing, the field is absent (an older backend), or the
 * value is not a sensible positive integer.
 */
export function resolveOtpCodeLength(
  source: Pick<AuthConfigDto, 'otpCodeLength'> | number | null | undefined,
): number {
  const value = typeof source === 'number' ? source : source?.otpCodeLength;
  if (typeof value !== 'number' || !Number.isInteger(value)) return DEFAULT_OTP_CODE_LENGTH;
  if (value < 1 || value > MAX_ACCEPTED_CODE_LENGTH) return DEFAULT_OTP_CODE_LENGTH;
  return value;
}

/**
 * Digits expected for a given two-factor / step-up method: TOTP is always
 * {@link TOTP_CODE_LENGTH}; every delivered code (SMS / email) follows the
 * deployment's `otpCodeLength`.
 */
export function codeLengthForMethod(method: string | null | undefined, otpCodeLength: number): number {
  return method === 'totp' ? TOTP_CODE_LENGTH : otpCodeLength;
}
