namespace Tnzi.AI.Device.Transport;

// ─── Device → Server (inbound) ────────────────────────────────────────────────

/// <summary>
/// First message sent by the device after connecting.
/// Carries the pairing code and self-reported capabilities.
/// </summary>
internal sealed class WsRegisterMessage
{
    public string Type { get; set; } = "register";

    /// <summary>Pairing code generated by the server-side pairing flow.</summary>
    public string PairingCode { get; set; } = string.Empty;

    /// <summary>Human-readable device name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Device platform string (Windows / MacOS / Linux / iOS / Android).</summary>
    public string Platform { get; set; } = string.Empty;

    /// <summary>Capabilities the device supports (family → commands).</summary>
    public List<WsCapabilityDto> Capabilities { get; set; } = [];
}

/// <summary>
/// Sent by the device in response to a <see cref="WsInvokeMessage"/>.
/// </summary>
internal sealed class WsResultMessage
{
    public string Type { get; set; } = "result";

    /// <summary>Matches <see cref="WsInvokeMessage.CorrelationId"/>.</summary>
    public string CorrelationId { get; set; } = string.Empty;

    public bool Success { get; set; }

    /// <summary>Text payload (may be null on success or failure).</summary>
    public string? TextResult { get; set; }

    /// <summary>Base64-encoded binary payload (optional).</summary>
    public string? BinaryResultBase64 { get; set; }

    /// <summary>MIME type when a binary result is returned.</summary>
    public string? MimeType { get; set; }

    /// <summary>Error message when <see cref="Success"/> is false.</summary>
    public string? Error { get; set; }
}

// ─── Server → Device (outbound) ───────────────────────────────────────────────

/// <summary>
/// Sent by the server to acknowledge a successful registration.
/// </summary>
internal sealed class WsRegisteredMessage
{
    public string Type { get; set; } = "registered";
    public string NodeId { get; set; } = string.Empty;
}

/// <summary>
/// Sent by the server to reject a registration attempt.
/// </summary>
internal sealed class WsRejectedMessage
{
    public string Type { get; set; } = "rejected";
    public string Reason { get; set; } = string.Empty;
}

/// <summary>
/// Sent by the server to invoke a capability on the remote device.
/// </summary>
internal sealed class WsInvokeMessage
{
    public string Type { get; set; } = "invoke";

    /// <summary>Unique correlation ID for matching <see cref="WsResultMessage"/>.</summary>
    public string CorrelationId { get; set; } = string.Empty;

    public string Family { get; set; } = string.Empty;
    public string Command { get; set; } = string.Empty;

    /// <summary>Optional parameters (raw JSON element).</summary>
    public JsonElement? Parameters { get; set; }

    /// <summary>Command timeout in seconds (informational for device-side enforcement).</summary>
    public int TimeoutSeconds { get; set; }
}

// ─── Shared DTO ───────────────────────────────────────────────────────────────

internal sealed class WsCapabilityDto
{
    public string Family { get; set; } = string.Empty;
    public List<string> Commands { get; set; } = [];
    public string Permission { get; set; } = "basic";
}
